global:
  scrape_interval:     10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:9100']

  - job_name: postgresql
    static_configs:
    - targets: ['localhost:9187']
      labels:
        alias: postgres